# Generated by Django 6.0.6 on 2026-07-06 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0002_alter_category_options_ticket_ticketattachment'),
        ('ticketapp', '0003_ticket_ticketattachment'),
    ]

    operations = [
    ]
