# Generated by Django 6.0.6 on 2026-07-06 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0005_productmaster'),
        ('ticketapp', '0006_productmaster'),
    ]

    operations = [
    ]
