# Generated by Django 6.0.6 on 2026-07-06 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0007_merge_0005_productmaster_0006_productmaster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='escalation_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ticketassignment',
            name='transferred_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_assignments_received_via_transfer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketassignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('unavailable', 'Unavailable'), ('transferred', 'Transferred')], default='pending', max_length=15),
        ),
    ]
