# Generated by Django 6.0.6 on 2026-07-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0010_ticket_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='product',
            field=models.CharField(blank=True, default='Not Applicable', max_length=150),
        ),
    ]
