# Generated by Django 6.0.6 on 2026-07-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0011_alter_ticket_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='product',
            field=models.CharField(max_length=150),
        ),
    ]
