# Generated by Django 6.0.6 on 2026-07-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0012_alter_ticket_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmaster',
            options={'ordering': ['name', 'version'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='productmaster',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='product',
            field=models.CharField(blank=True, default='Not Applicable', max_length=150),
        ),
        migrations.AddConstraint(
            model_name='productmaster',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='unique_product_name_version'),
        ),
    ]
