# Generated by Django 6.0.6 on 2026-07-08 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0009_ticketassignmentevent'),
        ('ticketapp', '0013_alter_productmaster_options_alter_productmaster_name_and_more'),
    ]

    operations = [
    ]
