# Generated by Django 6.0.6 on 2026-07-11 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0014_merge_20260708_1623'),
        ('ticketapp', '0014_merge_20260708_1629'),
    ]

    operations = [
    ]
