# Generated by Django 6.0.6 on 2026-07-14 14:01

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0016_loginactivity_staffactivitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginActivityProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Login Activity',
                'verbose_name_plural': 'Login Activity',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.loginactivity',),
        ),
        migrations.CreateModel(
            name='StaffActivityProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Staff Activity',
                'verbose_name_plural': 'Staff Activity',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.staffactivitylog',),
        ),
    ]
