# Generated by Django 6.0.6 on 2026-07-02 09:49

import authentication.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff'), ('admin', 'Admin')], default='customer', max_length=10)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', authentication.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=10)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('company_code', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('company_type', models.CharField(blank=True, choices=[('Private Limited', 'Private Limited'), ('Public Limited', 'Public Limited'), ('LLP', 'LLP'), ('Partnership', 'Partnership'), ('Sole Proprietorship', 'Sole Proprietorship'), ('Government', 'Government'), ('Non-Profit', 'Non-Profit')], max_length=30)),
                ('gst_number', models.CharField(blank=True, max_length=15)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('website', models.URLField(blank=True)),
                ('industry_type', models.CharField(blank=True, max_length=50)),
                ('annual_turnover', models.CharField(blank=True, max_length=30)),
                ('employee_count', models.CharField(blank=True, max_length=20)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, default='India', max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mobile_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('phone_number', models.CharField(blank=True, max_length=10)),
                ('alternate_email', models.EmailField(blank=True, max_length=254)),
                ('amc_status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Expired', 'Expired'), ('Not Applicable', 'Not Applicable')], max_length=20)),
                ('amc_start_date', models.DateField(blank=True, null=True)),
                ('amc_end_date', models.DateField(blank=True, null=True)),
                ('preferred_channel', models.CharField(blank=True, max_length=30)),
                ('preferred_time', models.CharField(blank=True, max_length=30)),
                ('remarks', models.TextField(blank=True, max_length=250)),
                ('products_in_use', models.JSONField(blank=True, default=list)),
                ('contract_ref_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_companies', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Mpin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpin_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mpin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mpins',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_version', models.CharField(blank=True, max_length=30)),
                ('activation_date', models.DateField(blank=True, null=True)),
                ('support_type', models.CharField(choices=[('AMC', 'AMC'), ('NON-AMC', 'NON-AMC'), ('SAS', 'SAS')], default='AMC', max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='authentication.company')),
            ],
            options={
                'db_table': 'company_products',
            },
        ),
    ]
