# Generated by Django 6.0.6 on 2026-07-02 08:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_mpin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=10)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('company_code', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('company_type', models.CharField(blank=True, choices=[('Private Limited', 'Private Limited'), ('Public Limited', 'Public Limited'), ('LLP', 'LLP'), ('Partnership', 'Partnership'), ('Sole Proprietorship', 'Sole Proprietorship'), ('Government', 'Government'), ('Non-Profit', 'Non-Profit')], max_length=30)),
                ('gst_number', models.CharField(blank=True, max_length=15)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('website', models.URLField(blank=True)),
                ('industry_type', models.CharField(blank=True, max_length=50)),
                ('annual_turnover', models.CharField(blank=True, max_length=30)),
                ('employee_count', models.CharField(blank=True, max_length=20)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, default='India', max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mobile_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('phone_number', models.CharField(blank=True, max_length=10)),
                ('alternate_email', models.EmailField(blank=True, max_length=254)),
                ('amc_status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Expired', 'Expired'), ('Not Applicable', 'Not Applicable')], max_length=20)),
                ('amc_start_date', models.DateField(blank=True, null=True)),
                ('amc_end_date', models.DateField(blank=True, null=True)),
                ('preferred_channel', models.CharField(blank=True, max_length=30)),
                ('preferred_time', models.CharField(blank=True, max_length=30)),
                ('remarks', models.TextField(blank=True, max_length=250)),
                ('products_in_use', models.JSONField(blank=True, default=list)),
                ('contract_ref_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_companies', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_version', models.CharField(blank=True, max_length=30)),
                ('activation_date', models.DateField(blank=True, null=True)),
                ('support_type', models.CharField(choices=[('AMC', 'AMC'), ('NON-AMC', 'NON-AMC'), ('SAS', 'SAS')], default='AMC', max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='authentication.company')),
            ],
            options={
                'db_table': 'company_products',
            },
        ),
    ]
