# Generated by Django 6.0.6 on 2026-07-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_company_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='product_verification',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='company',
            name='verification_note',
            field=models.TextField(blank=True),
        ),
    ]
