# Generated by Django 6.0.6 on 2026-07-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_emailotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('mpin_change', 'M-PIN Change'), ('mpin_forgot', 'M-PIN Forgot/Reset')], max_length=20),
        ),
    ]
