# Generated by Django 6.0.6 on 2026-07-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_staffproduct'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staffproduct',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='staffproduct',
            name='version',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='staffproduct',
            unique_together={('staff', 'product_name', 'version')},
        ),
    ]
