# Generated by Django 6.0.6 on 2026-07-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_staffproduct_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
