# Generated by Django 6.0.6 on 2026-07-14 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_company_rejection_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='rejection_reason',
        ),
        migrations.CreateModel(
            name='RejectedRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('company_type', models.CharField(blank=True, max_length=30)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mobile_number', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rejected_registrations',
                'ordering': ['-rejected_at'],
            },
        ),
    ]
