# Generated by Django 6.0.6 on 2026-07-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_remove_company_rejection_reason_rejectedregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='RejectedRegistration',
        ),
    ]
