# Generated by Django 6.0.6 on 2026-07-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_company_rejection_reason_delete_rejectedregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='amc_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='support_type',
            field=models.CharField(default='AMC', max_length=10),
        ),
        migrations.CreateModel(
            name='DropdownOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('company_type', 'Company Type'), ('industry_type', 'Industry Type'), ('turnover_range', 'Annual Turnover'), ('employee_range', 'No. of Employees'), ('amc_status', 'AMC Status'), ('support_channel', 'Preferred Support Channel'), ('support_time', 'Preferred Support Time'), ('support_type', 'Support Type')], max_length=30)),
                ('value', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dropdown Option',
                'verbose_name_plural': 'Dropdown Options',
                'db_table': 'dropdown_options',
                'ordering': ['category', 'display_order', 'id'],
                'unique_together': {('category', 'value')},
            },
        ),
    ]
