# Generated by Django 6.0.6 on 2026-07-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_loginactivity_staffactivitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('logo', models.ImageField(blank=True, help_text="Shown at the bottom of the registration-received and account-approved emails. Best results: a square PNG or JPG at least 200×200px with a plain or transparent background. Anything larger is automatically resized to fit, so there's no need to pre-crop it.", null=True, upload_to='company_contact/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Contact Details',
                'verbose_name_plural': 'Email Contact Details',
                'db_table': 'company_contact_settings',
            },
        ),
    ]
