# Generated by Django 6.0.6 on 2026-07-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_companycontactsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active_device_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
