# Generated by Django 6.0.6 on 2026-07-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_customuser_active_device_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPasswordSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(default='tixa@1234', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Report Password',
                'verbose_name_plural': 'Report Password',
                'db_table': 'report_password_settings',
            },
        ),
    ]
