# Generated by Django 6.0.6 on 2026-07-15 01:55

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0017_companycontactsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyContactSettingsProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Email Contact Details',
                'verbose_name_plural': 'Email Contact Details',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.companycontactsettings',),
        ),
    ]
