# Generated by Django 6.0.6 on 2026-07-15 11:12

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0019_reportpasswordsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPasswordSettingsProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Report Password',
                'verbose_name_plural': 'Report Password',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.reportpasswordsettings',),
        ),
    ]
