# Generated by Django 6.0.6 on 2026-07-14 14:01

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0016_loginactivity_staffactivitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropdownOptionProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Dropdown Option',
                'verbose_name_plural': 'Dropdown Options',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.dropdownoption',),
        ),
    ]
